/*
 * This file is generated by jOOQ.
*/
package com.generator.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Book implements Serializable {

    private static final long serialVersionUID = 2142008542;

    private Integer id;
    private Integer authorId;
    private String  title;
    private Integer langueId;
    private Integer languageId;

    public Book() {}

    public Book(Book value) {
        this.id = value.id;
        this.authorId = value.authorId;
        this.title = value.title;
        this.langueId = value.langueId;
        this.languageId = value.languageId;
    }

    public Book(
        Integer id,
        Integer authorId,
        String  title,
        Integer langueId,
        Integer languageId
    ) {
        this.id = id;
        this.authorId = authorId;
        this.title = title;
        this.langueId = langueId;
        this.languageId = languageId;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getAuthorId() {
        return this.authorId;
    }

    public void setAuthorId(Integer authorId) {
        this.authorId = authorId;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public Integer getLangueId() {
        return this.langueId;
    }

    public void setLangueId(Integer langueId) {
        this.langueId = langueId;
    }

    public Integer getLanguageId() {
        return this.languageId;
    }

    public void setLanguageId(Integer languageId) {
        this.languageId = languageId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Book (");

        sb.append(id);
        sb.append(", ").append(authorId);
        sb.append(", ").append(title);
        sb.append(", ").append(langueId);
        sb.append(", ").append(languageId);

        sb.append(")");
        return sb.toString();
    }
}
