/*
 * This file is generated by jOOQ.
*/
package com.generator;


import com.generator.tables.Author;
import com.generator.tables.Book;
import com.generator.tables.SchemaVersion;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JooqFlyway extends SchemaImpl {

    private static final long serialVersionUID = 672215792;

    /**
     * The reference instance of <code>jooq_flyway</code>
     */
    public static final JooqFlyway JOOQ_FLYWAY = new JooqFlyway();

    /**
     * The table <code>jooq_flyway.author</code>.
     */
    public final Author AUTHOR = com.generator.tables.Author.AUTHOR;

    /**
     * The table <code>jooq_flyway.book</code>.
     */
    public final Book BOOK = com.generator.tables.Book.BOOK;

    /**
     * The table <code>jooq_flyway.schema_version</code>.
     */
    public final SchemaVersion SCHEMA_VERSION = com.generator.tables.SchemaVersion.SCHEMA_VERSION;

    /**
     * No further instances allowed
     */
    private JooqFlyway() {
        super("jooq_flyway", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Author.AUTHOR,
            Book.BOOK,
            SchemaVersion.SCHEMA_VERSION);
    }
}
